apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
    name: https-only
    namespace: keycloak
    labels: 
      global: "true"
    annotations:
      kubernetes.io/ingress.class: "kong"
route:
  methods:
   - GET
   - POST
   - PUT
  protocols:
  - https
  https_redirect_status_code: 302
proxy:
  protocol: "http"
  path: "/test"
  connect_timeout: 10000
  retries: 10
  read_timeout: 10000
  write_timeout: 10000