apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: route-redirect
route:
  protocols:
  - https
  https_redirect_status_code: 302
proxy:
  protocol: https
  path: "/test"
  connect_timeout: 10000
  retries: 10
  read_timeout: 10000
  write_timeout: 10000